const types = {
  SET_USER_ACCESS_TOKEN: 'SET_USER_ACCESS_TOKEN',

  SET_USER_DETAILS: 'SET_USER_DETAILS',

  SET_USER_REPOS: 'SET_USER_REPOS',

  FETCH_IN_PROGRESS: 'FETCH_IN_PROGRESS',
  FETCH_RESPONDED: 'FETCH_RESPONDED',
  FETCH_RESPONDED_WITH_ERR: 'FETCH_RESPONDED_WITH_ERR',
};

export default types;
